In [1]:
import pandas as pd, numpy as np, random as rnd
train=pd.read_csv('train.csv')
X_test=pd.read_csv('test.csv')
y_test=pd.read_csv('gender_submission.csv')
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
X_train, y_train=train.drop(['Survived', 'Name', 'Ticket', 'Cabin'], axis=1), train['Survived']
X_train.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1       3    male  22.0      1      0   7.2500        S
1            2       1  female  38.0      1      0  71.2833        C
2            3       3  female  26.0      0      0   7.9250        S
3            4       1  female  35.0      1      0  53.1000        S
4            5       3    male  35.0      0      0   8.0500        S

In [3]:
mu=train['Age'].mean()
sigma=np.sqrt(train['Age'].var())
rnd_norm=[]
while len(rnd_norm)!=177:
    x=rnd.normalvariate(mu,sigma)
    if x<=0.:
        continue
    rnd_norm.append(x)
k=0
for idx, el in enumerate(X_train['Age']):
    if np.isnan(el):
        X_train['Age'][idx]=rnd_norm[k]
        k+=1

C:\Users\gost_\Anaconda2\lib\site-packages\ipykernel\__main__.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [4]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
PassengerId    891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [5]:
X_train['Fare']=X_train['Fare'].fillna(0.)
X_train['Embarked']=X_train['Embarked'].fillna('S')
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
PassengerId    891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       891 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [6]:
Categ=X_train[['Sex', 'Embarked']].astype(str)
X_train=X_train.drop(['Sex', 'Embarked'], axis=1)
from sklearn.feature_extraction import DictVectorizer as DV
encoder = DV(sparse = False)
enc_data=encoder.fit_transform(Categ.T.to_dict().values())
X_train=np.hstack((X_train, enc_data))
print enc_data, '\n\n', X_train

[[ 0.  0.  1.  0.  1.]
 [ 1.  0.  0.  1.  0.]
 [ 0.  0.  1.  1.  0.]
 ..., 
 [ 0.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.]] 

[[   1.            3.           22.         ...,    1.            0.            1.        ]
 [   2.            1.           38.         ...,    0.            1.            0.        ]
 [   3.            3.           26.         ...,    1.            1.            0.        ]
 ..., 
 [ 889.            3.           36.92641001 ...,    1.            1.            0.        ]
 [ 890.            1.           26.         ...,    0.            0.            1.        ]
 [ 891.            3.           32.         ...,    0.            0.            1.        ]]


In [7]:
X_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [8]:
X_test=X_test.drop(['Name', 'Ticket', 'Cabin'], axis=1)
X_test['Fare']=X_test['Fare'].fillna(0.)
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           418 non-null float64
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 26.2+ KB


In [9]:
mu1=X_test['Age'].mean()
sigma1=np.sqrt(X_test['Age'].var())
rnd_norm1=[]
while len(rnd_norm1)!=177:
    x=rnd.normalvariate(mu1,sigma1)
    if x<=0.:
        continue
    rnd_norm1.append(x)
k=0
for idx, el in enumerate(X_test['Age']):
    if np.isnan(el):
        X_test['Age'][idx]=rnd_norm1[k]
        k+=1
X_test.info()

C:\Users\gost_\Anaconda2\lib\site-packages\ipykernel\__main__.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Sex            418 non-null object
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           418 non-null float64
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 26.2+ KB


In [10]:
X_test.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0          892       3    male  34.5      0      0   7.8292        Q
1          893       3  female  47.0      1      0   7.0000        S
2          894       2    male  62.0      0      0   9.6875        Q
3          895       3    male  27.0      0      0   8.6625        S
4          896       3  female  22.0      1      1  12.2875        S

In [11]:
Categ1=X_test[['Sex', 'Embarked']].astype(str)
X_test=X_test.drop(['Sex', 'Embarked'], axis=1)
X_test.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare
0          892       3  34.5      0      0   7.8292
1          893       3  47.0      1      0   7.0000
2          894       2  62.0      0      0   9.6875
3          895       3  27.0      0      0   8.6625
4          896       3  22.0      1      1  12.2875

In [12]:
Categ1.head()

Sex Embarked
0    male        Q
1  female        S
2    male        Q
3    male        S
4  female        S

In [13]:
from sklearn.feature_extraction import DictVectorizer as DV
encoder = DV(sparse = False)
enc_data1=encoder.fit_transform(Categ1.T.to_dict().values())
X_test=np.hstack((X_test, enc_data1))
print enc_data1, '\n\n', X_test

[[ 0.  1.  0.  0.  1.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  1.  0.  0.  1.]
 ..., 
 [ 0.  0.  1.  0.  1.]
 [ 0.  0.  1.  0.  1.]
 [ 1.  0.  0.  0.  1.]] 

[[  8.92000000e+02   3.00000000e+00   3.45000000e+01 ...,   0.00000000e+00
    0.00000000e+00   1.00000000e+00]
 [  8.93000000e+02   3.00000000e+00   4.70000000e+01 ...,   1.00000000e+00
    1.00000000e+00   0.00000000e+00]
 [  8.94000000e+02   2.00000000e+00   6.20000000e+01 ...,   0.00000000e+00
    0.00000000e+00   1.00000000e+00]
 ..., 
 [  1.30700000e+03   3.00000000e+00   3.85000000e+01 ...,   1.00000000e+00
    0.00000000e+00   1.00000000e+00]
 [  1.30800000e+03   3.00000000e+00   2.29587721e+01 ...,   1.00000000e+00
    0.00000000e+00   1.00000000e+00]
 [  1.30900000e+03   3.00000000e+00   3.90182447e+01 ...,   0.00000000e+00
    0.00000000e+00   1.00000000e+00]]


In [14]:
y_test=y_test['Survived']

In [15]:
from sklearn.linear_model import RidgeClassifier
clf=RidgeClassifier()
y_train=y_train.astype(int)
y_test=y_test.astype(int)
clf.fit(X_train, y_train)

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
        max_iter=None, normalize=False, random_state=None, solver='auto',
        tol=0.001)

In [16]:
res=clf.predict(X_test)
print res

[0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 1 1 0 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1 1 0 1 1
 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]


In [17]:
from sklearn.metrics import roc_auc_score
auc=roc_auc_score(y_true=y_test, y_score=res)
print 'auc =', auc

auc = 0.963345864662
